### ISSUE TITLE
Autocompletion breaks with native functions

### ISSUE THREAD

**Issue by jimafisk** [phpactor/ncm2-phpactor#21]
The autocomplete suggestions stop working when in the same `if` statement as php functions like [file_get_contents](https://www.php.net/manual/en/function.file-get-contents.php) or [trim](https://www.php.net/manual/en/function.trim.php) for example.

With code containing functions commented out, the completion works:

![working_completion](https://user-images.githubusercontent.com/5913244/57389401-14cd4a80-7188-11e9-9f5f-b198b0f01ee0.png)

However it does not give any suggestions in functions are present:

![no_suggestions](https://user-images.githubusercontent.com/5913244/57389419-23b3fd00-7188-11e9-855d-290bfa5034e6.png)

**Comment by dantleech** [comment]
This is likely a problem with Phpactor itself rather than this integration.

It may be that Phpactor is experiencing an error. To further investigate could you run Phpactor with [replay](https://phpactor.github.io/phpactor/developing.html#debugging-rpc) enabled, follow the instructions there and see if any errors are dislayed?

**Comment by jimafisk** [comment]
Thanks @dantleech! I got replay working by creating a `.phpactor.yml` file in the base directory of my project and adding `rpc.store_replay: true` to it. 

It was giving me an error that replay file was missing at `~/.cache/phpactor/replay.json` because it does seem to write to this file for the ncm2 autocomplete commands. I've tried to replicate what ncm2-phpactor is doing automatically, but please let me know if I did something incorrectly.

In neovim, in the section that's broken I wrote `\Drupal` then got out of insert mode, put the cursor over it and ran `:call phpactor#ContextMenu()`. In neovim I get this error:
```
Error from Phpactor: File "/home/jimafisk/.vim/bundle/phpactor/vendor/jetbrains/phpstorm-stubs/standard/standard_5.php" does not exist
```

Running `~/.config/nvim/plugged/phpactor/bin/phpactor rpc --replay` returns:
```
{"version":"1.0.0","action":"error","parameters":{"message":"File \"\/home\/jimafisk\/.vim\/bundle\/phpactor\/vendor\/jetbrains\/phpstorm-stubs\/standard\/standard_5.php\" does not exist","details":"0: File \"\/home\/jimafisk\/.vim\/bundle\/phpactor\/vendor\/jetbrains\/phpstorm-stubs\/standard\/standard_5.php\" does not exist\n#0 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/SourceCodeLocator\/StubSourceLocator.php(40): Phpactor\\WorseReflection\\Core\\SourceCode::fromPath('\/home\/jimafisk\/...')\n#1 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/SourceCodeLocator\/ChainSourceLocator.php(33): Phpactor\\WorseReflection\\Core\\SourceCodeLocator\\StubSourceLocator->locate(Object(Phpactor\\WorseReflection\\Core\\Name))\n#2 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/SourceCodeLocator\/ChainSourceLocator.php(33): Phpactor\\WorseReflection\\Core\\SourceCodeLocator\\ChainSourceLocator->locate(Object(Phpactor\\WorseReflection\\Core\\Name))\n#3 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Reflector\/CoreReflector.php(178): Phpactor\\WorseReflection\\Core\\SourceCodeLocator\\ChainSourceLocator->locate(Object(Phpactor\\WorseReflection\\Core\\Name))\n#4 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Reflector\/ClassReflector\/MemonizedReflector.php(104): Phpactor\\WorseReflection\\Core\\Reflector\\CoreReflector->reflectFunction(Object(Phpactor\\WorseReflection\\Core\\Name))\n#5 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Reflector\/CompositeReflector.php(109): Phpactor\\WorseReflection\\Core\\Reflector\\ClassReflector\\MemonizedReflector->reflectFunction(Object(Phpactor\\WorseReflection\\Core\\Name))\n#6 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Inference\/SymbolContextResolver.php(324): Phpactor\\WorseReflection\\Core\\Reflector\\CompositeReflector->reflectFunction(Object(Phpactor\\WorseReflection\\Core\\Name))\n#7 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Inference\/SymbolContextResolver.php(125): Phpactor\\WorseReflection\\Core\\Inference\\SymbolContextResolver->resolveQualfiedName(Object(Phpactor\\WorseReflection\\Core\\Inference\\Frame), Object(Microsoft\\PhpParser\\Node\\QualifiedName))\n#8 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Inference\/SymbolContextResolver.php(113): Phpactor\\WorseReflection\\Core\\Inference\\SymbolContextResolver->__resolveNode(Object(Phpactor\\WorseReflection\\Core\\Inference\\Frame), Object(Microsoft\\PhpParser\\Node\\QualifiedName))\n#9 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Inference\/SymbolContextResolver.php(306): Phpactor\\WorseReflection\\Core\\Inference\\SymbolContextResolver->_resolveNode(Object(Phpactor\\WorseReflection\\Core\\Inference\\Frame), Object(Microsoft\\PhpParser\\Node\\QualifiedName))\n#10 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Inference\/SymbolContextResolver.php(159): Phpactor\\WorseReflection\\Core\\Inference\\SymbolContextResolver->resolveCallExpression(Object(Phpactor\\WorseReflection\\Core\\Inference\\Frame), Object(Microsoft\\PhpParser\\Node\\Expression\\CallExpression))\n#11 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Inference\/SymbolContextResolver.php(113): Phpactor\\WorseReflection\\Core\\Inference\\SymbolContextResolver->__resolveNode(Object(Phpactor\\WorseReflection\\Core\\Inference\\Frame), Object(Microsoft\\PhpParser\\Node\\Expression\\CallExpression))\n#12 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Inference\/SymbolContextResolver.php(97): Phpactor\\WorseReflection\\Core\\Inference\\SymbolContextResolver->_resolveNode(Object(Phpactor\\WorseReflection\\Core\\Inference\\Frame), Object(Microsoft\\PhpParser\\Node\\Expression\\CallExpression))\n#13 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Inference\/FrameBuilder.php(107): Phpactor\\WorseReflection\\Core\\Inference\\SymbolContextResolver->resolveNode(Object(Phpactor\\WorseReflection\\Core\\Inference\\Frame), Object(Microsoft\\PhpParser\\Node\\Expression\\CallExpression))\n#14 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Inference\/FrameBuilder\/AssignmentWalker.php(44): Phpactor\\WorseReflection\\Core\\Inference\\FrameBuilder->resolveNode(Object(Phpactor\\WorseReflection\\Core\\Inference\\Frame), Object(Microsoft\\PhpParser\\Node\\Expression\\CallExpression))\n#15 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Inference\/FrameBuilder.php(78): Phpactor\\WorseReflection\\Core\\Inference\\FrameBuilder\\AssignmentWalker->walk(Object(Phpactor\\WorseReflection\\Core\\Inference\\FrameBuilder), Object(Phpactor\\WorseReflection\\Core\\Inference\\Frame), Object(Microsoft\\PhpParser\\Node\\Expression\\AssignmentExpression))\n#16 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Inference\/FrameBuilder.php(83): Phpactor\\WorseReflection\\Core\\Inference\\FrameBuilder->walkNode(Object(Microsoft\\PhpParser\\Node\\Expression\\AssignmentExpression), Object(Microsoft\\PhpParser\\Node\\QualifiedName), Object(Phpactor\\WorseReflection\\Core\\Inference\\Frame))\n#17 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Inference\/FrameBuilder.php(83): Phpactor\\WorseReflection\\Core\\Inference\\FrameBuilder->walkNode(Object(Microsoft\\PhpParser\\Node\\Statement\\ExpressionStatement), Object(Microsoft\\PhpParser\\Node\\QualifiedName), Object(Phpactor\\WorseReflection\\Core\\Inference\\Frame))\n#18 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Inference\/FrameBuilder.php(83): Phpactor\\WorseReflection\\Core\\Inference\\FrameBuilder->walkNode(Object(Microsoft\\PhpParser\\Node\\Statement\\CompoundStatementNode), Object(Microsoft\\PhpParser\\Node\\QualifiedName), Object(Phpactor\\WorseReflection\\Core\\Inference\\Frame))\n#19 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Inference\/FrameBuilder.php(83): Phpactor\\WorseReflection\\Core\\Inference\\FrameBuilder->walkNode(Object(Microsoft\\PhpParser\\Node\\Statement\\IfStatementNode), Object(Microsoft\\PhpParser\\Node\\QualifiedName), Object(Phpactor\\WorseReflection\\Core\\Inference\\Frame))\n#20 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Inference\/FrameBuilder.php(83): Phpactor\\WorseReflection\\Core\\Inference\\FrameBuilder->walkNode(Object(Microsoft\\PhpParser\\Node\\CaseStatementNode), Object(Microsoft\\PhpParser\\Node\\QualifiedName), Object(Phpactor\\WorseReflection\\Core\\Inference\\Frame))\n#21 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Inference\/FrameBuilder.php(83): Phpactor\\WorseReflection\\Core\\Inference\\FrameBuilder->walkNode(Object(Microsoft\\PhpParser\\Node\\Statement\\SwitchStatementNode), Object(Microsoft\\PhpParser\\Node\\QualifiedName), Object(Phpactor\\WorseReflection\\Core\\Inference\\Frame))\n#22 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Inference\/FrameBuilder.php(83): Phpactor\\WorseReflection\\Core\\Inference\\FrameBuilder->walkNode(Object(Microsoft\\PhpParser\\Node\\Statement\\CompoundStatementNode), Object(Microsoft\\PhpParser\\Node\\QualifiedName), Object(Phpactor\\WorseReflection\\Core\\Inference\\Frame))\n#23 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Inference\/FrameBuilder.php(83): Phpactor\\WorseReflection\\Core\\Inference\\FrameBuilder->walkNode(Object(Microsoft\\PhpParser\\Node\\Statement\\IfStatementNode), Object(Microsoft\\PhpParser\\Node\\QualifiedName), Object(Phpactor\\WorseReflection\\Core\\Inference\\Frame))\n#24 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Inference\/FrameBuilder.php(83): Phpactor\\WorseReflection\\Core\\Inference\\FrameBuilder->walkNode(Object(Microsoft\\PhpParser\\Node\\Statement\\CompoundStatementNode), Object(Microsoft\\PhpParser\\Node\\QualifiedName), Object(Phpactor\\WorseReflection\\Core\\Inference\\Frame))\n#25 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Inference\/FrameBuilder.php(61): Phpactor\\WorseReflection\\Core\\Inference\\FrameBuilder->walkNode(Object(Microsoft\\PhpParser\\Node\\Statement\\FunctionDeclaration), Object(Microsoft\\PhpParser\\Node\\QualifiedName))\n#26 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Bridge\/TolerantParser\/Reflector\/TolerantSourceCodeReflector.php(60): Phpactor\\WorseReflection\\Core\\Inference\\FrameBuilder->build(Object(Microsoft\\PhpParser\\Node\\QualifiedName))\n#27 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Reflector\/SourceCode\/ContextualSourceCodeReflector.php(52): Phpactor\\WorseReflection\\Bridge\\TolerantParser\\Reflector\\TolerantSourceCodeReflector->reflectOffset(Object(Phpactor\\WorseReflection\\Core\\SourceCode), Object(Phpactor\\WorseReflection\\Core\\Offset))\n#28 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/worse-reflection\/lib\/Core\/Reflector\/CompositeReflector.php(88): Phpactor\\WorseReflection\\Core\\Reflector\\SourceCode\\ContextualSourceCodeReflector->reflectOffset(Object(Phpactor\\WorseReflection\\Core\\SourceCode), Object(Phpactor\\WorseReflection\\Core\\Offset))\n#29 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/lib\/Extension\/ContextMenu\/Handler\/ContextMenuHandler.php(143): Phpactor\\WorseReflection\\Core\\Reflector\\CompositeReflector->reflectOffset(Object(Phpactor\\WorseReflection\\Core\\SourceCode), Object(Phpactor\\WorseReflection\\Core\\Offset))\n#30 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/lib\/Extension\/ContextMenu\/Handler\/ContextMenuHandler.php(81): Phpactor\\Extension\\ContextMenu\\Handler\\ContextMenuHandler->offsetFromSourceAndOffset('<?php\\n\\n\/**\\n * @...', 1157, '\/home\/jimafisk\/...')\n#31 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/rpc-extension\/lib\/RequestHandler\/RequestHandler.php(33): Phpactor\\Extension\\ContextMenu\\Handler\\ContextMenuHandler->handle(Array)\n#32 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/rpc-extension\/lib\/RequestHandler\/ExceptionCatchingHandler.php(25): Phpactor\\Extension\\Rpc\\RequestHandler\\RequestHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#33 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/rpc-extension\/lib\/RequestHandler\/LoggingHandler.php(39): Phpactor\\Extension\\Rpc\\RequestHandler\\ExceptionCatchingHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#34 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/rpc-extension\/lib\/Command\/RpcCommand.php(86): Phpactor\\Extension\\Rpc\\RequestHandler\\LoggingHandler->handle(Object(Phpactor\\Extension\\Rpc\\Request))\n#35 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/phpactor\/rpc-extension\/lib\/Command\/RpcCommand.php(68): Phpactor\\Extension\\Rpc\\Command\\RpcCommand->processRequest(Object(Phpactor\\Extension\\Rpc\\Request))\n#36 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/symfony\/console\/Command\/Command.php(255): Phpactor\\Extension\\Rpc\\Command\\RpcCommand->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#37 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/symfony\/console\/Application.php(901): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#38 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/symfony\/console\/Application.php(262): Symfony\\Component\\Console\\Application->doRunCommand(Object(Phpactor\\Extension\\Rpc\\Command\\RpcCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#39 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/lib\/Application.php(50): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#40 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/vendor\/symfony\/console\/Application.php(145): Phpactor\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#41 \/home\/jimafisk\/.config\/nvim\/plugged\/phpactor\/bin\/phpactor(41): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))\n#42 {main}"}}
```
---

To contrast, if I `:call phpactor#ContextMenu()` in the section that works with ncm2-phpactor I get the following in neovim:
```
Class "\Drupal":                                                                                                                                                         
[o]verride_method, (r)eplace_references, (f)ind_references, (m)ove, (h)over, (c)opy, (i)nflect, c(l)ass_new, (t)ransform_file, (g)oto_definition, (n)avigate, im(p)ort:
```
And `~/.config/nvim/plugged/phpactor/bin/phpactor rpc --replay` gives:
```
{"version":"1.0.0","action":"input_callback","parameters":{"inputs":[{"name":"action","type":"choice","parameters":{"default":null,"label":"Class \"\\Drupal\":","choices":{"class_new":"class_new","copy":"copy","find_references":"find_references","goto_definition":"goto_definition","inflect":"inflect","move":"move","navigate":"navigate","override_method":"override_method","replace_references":"replace_references","transform_file":"transform_file","import":"import","hover":"hover"}}}],"callback":{"action":"context_menu","parameters":{"source":"<?php\n\n\/**\n * @file\n * The Base module file for bos_messages module.\n *\/\n\nuse Drupal\\Component\\Utility\\Xss;\n\n\/**\n * Implements hook_theme().\n *\/\nfunction bos_messages_theme($existing, $type, $theme, $path) {\n  return [\n    'bos_messages_mod_recur_widget' => [\n      'render element' => 'widget',\n    ],\n    'paragraph__message_for_the_day' => [\n      'base hook' => 'paragraph',\n      'path' => drupal_get_path('module', 'bos_messages') . '\/templates',\n    ],\n  ];\n}\n\n\/**\n * Implements hook_preprocess_paragraph().\n *\/\nfunction bos_messages_preprocess_paragraph(&$vars) {\n  if (!empty($vars['paragraph'])) {\n    $paragraph = $vars['paragraph'];\n    switch ($paragraph->bundle()) {\n      case 'message_for_the_day':\n        if (!$paragraph->get('field_link')->isEmpty()) {\n          $link = _bos_core_paragraph_extract_link($paragraph->get('field_link')->getValue());\n          $vars['card_url'] = $link['url'];\n          \\Drupal\n        }\n        if ($paragraph->get('field_use_alert')->Getvalue()['0']['value']) {\n          $alert = file_get_contents(drupal_get_path('module', 'bos_messages') . '\/assets\/alert.svg');\n          $vars['alert'] = trim($alert);\n        }\n        if ($host = $paragraph->getParentEntity()) {\n          if ($host->hasField('field_icon') && !$host->get('field_icon')->isEmpty()) {\n            $fid = $host->get('field_icon')->getValue()['0']['target_id'];\n            $uri = Drupal::entityTypeManager()->getStorage('file')->load($fid)->getFileUri();\n            $uri = \\Drupal::service('file_system')->realpath($uri);\n            $icon = file_get_contents($uri);\n            $vars['icon'] = Xss::filter($icon, explode(' ', BOS_CORE_SVG_ELEMENTS));\n          }\n          $vars['title'] = $host->label();\n        }\n        break;\n    }\n  }\n}","offset":925,"current_path":"\/home\/jimafisk\/Projects\/boston\/boston.gov-d8\/docroot\/modules\/custom\/bos_components\/modules\/bos_messages\/bos_messages.module"}}}}
```

**Comment by jimafisk** [comment]
I took another stab at this, turns out phpactor was looking in the wrong location for standard php. It was looking in `~/.vim/bundle/phpactor/vendor/jetbrains/phpstorm-stubs/standard/` but since I'm now using neovim, my stubs are located at: `~/.config/nvim/plugged/phpactor/vendor/jetbrains/phpstorm-stubs/standard/`.

I found this post which really helped me out: https://github.com/phpactor/phpactor/issues/510#issuecomment-401251377

To resolved my issue, I just needed to:
1. `cd ~/.config/nvim/plugged/phpactor/`
2. `./bin/phpactor cache:clear`
